# Generated by Django 4.2.6 on 2023-10-24 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miapp', '0002_comunicado'),
    ]

    operations = [
        migrations.CreateModel(
            name='Informaticas',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=30)),
                ('detalle', models.CharField(max_length=250)),
                ('detalle_corto', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Mecanicas',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=30)),
                ('detalle', models.CharField(max_length=250)),
                ('detalle_corto', models.CharField(max_length=50)),
            ],
        ),
        migrations.RenameModel(
            old_name='Comunicado',
            new_name='Electronicas',
        ),
        migrations.RemoveField(
            model_name='docente',
            name='carrera',
        ),
        migrations.DeleteModel(
            name='Carrera',
        ),
        migrations.DeleteModel(
            name='Docente',
        ),
    ]
