# Generated by Django 4.2.6 on 2023-10-24 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miapp', '0008_informaticas_entidad_mecanicas_entidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='electronicas',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='logos'),
        ),
        migrations.AddField(
            model_name='informaticas',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='logos'),
        ),
        migrations.AddField(
            model_name='mecanicas',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='logos'),
        ),
    ]
