# Generated by Django 4.2.6 on 2023-10-24 15:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('miapp', '0010_alter_electronicas_logo_alter_informaticas_logo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entidades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.group')),
            ],
        ),
        migrations.DeleteModel(
            name='Entidad',
        ),
    ]
