# Generated by Django 4.2.6 on 2023-10-24 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miapp', '0011_entidades_delete_entidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entidades',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
